# Generated by Django 2.2 on 2019-04-22 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0002_wishlist_user'),
        ('users', '0002_wishlistowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistowner',
            name='wishlists',
            field=models.ManyToManyField(to='wishlists.Wishlist'),
        ),
        migrations.AlterField(
            model_name='wishlistowner',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
