# Generated by Django 2.2 on 2019-04-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0002_wishlist_user'),
        ('users', '0003_auto_20190422_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wishlists',
            field=models.ManyToManyField(to='wishlists.Wishlist'),
        ),
        migrations.DeleteModel(
            name='WishListOwner',
        ),
    ]
