# Generated by Django 2.2 on 2019-04-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190422_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='wishlists',
            field=models.ManyToManyField(related_name='wishlists', to='wishlists.Wishlist'),
        ),
    ]
