dist: xenial
language: python
python:
  "3.7"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master

notifications:
  email: false

script:
  - python ./varwish/manage.py makemigrations
  - python ./varwish/manage.py migrate
  - python ./varwish/manage.py test 
  - python ./varwish/manage.py check --deploy 
