# Generated by Django 2.2 on 2019-04-20 20:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('em', 'Empty'), ('op', 'Open'), ('co', 'Completed'), ('cl', 'Closed')], default='em', max_length=2)),
            ],
        ),
    ]
