# Generated by Django 2.2 on 2019-04-22 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0003_auto_20190422_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='items',
        ),
        migrations.AddField(
            model_name='item',
            name='wishlist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wishlists.Wishlist'),
            preserve_default=False,
        ),
    ]
